# Generated by Django 5.0.2 on 2025-05-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('date_received', models.DateTimeField()),
                ('status', models.CharField(default='Applied', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
